### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by wise-introvert** [manigedit/cowin-slots#5]
Love the idea and would love to contribute but not sure if you are accepting contributions. Can you please let me know if you are, would love to help :smiley:!

BTW: great idea, beautifully executed! Kudos to you!

**Comment by manigedit** [comment]
@wise-introvert ! we'd be more than happy to have contributors. I'm really running out of time due to my full time job. Let's take this forward to a pan-india project

**Comment by wise-introvert** [comment]
@manigedit I can totally relate to the lack-of-time problem. Being a full-time employee myself, I'll only be able to work on this on the weekends, is that fine?

**Comment by manigedit** [comment]
Yeah please.

**Comment by wise-introvert** [comment]
@manigedit Great! Feel free to assign issues to me and I'll give them my best :smiley:
